In [1]:
# ==============================================================
# 📘 Numpy --> Python Basic To Advanced
# Author: Muhammad Shah Asyraf
# Credit: Yash Sharma
# Artificial Intelligence & Machine Learning Course
# ==============================================================

In [2]:
# NUMPY --> Numerical Python
import numpy as np
# numpy provides the support for most powerful data structure -- array
arr = np.array([10,20,30,40,50])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50]


In [3]:
# Python Numpy Vs List
numbers = [1, 2, 3, 4, 5]
total = 0
for n in numbers:
 total += n 
print(total)

15


In [4]:
numbers = np.array([1, 2, 3, 4, 5])
print(np.sum(numbers))

15


In [5]:
# how much execution time will it take
import time
numbers = list(range(1, 100000000))  # 1 2 3 4 5..................9999
total = 0
start_time = time.time() # record start time
for n in numbers:
    total += n
end_time = time.time() # record end time
print("Total:", total)
print("Execution Time:", end_time - start_time, "seconds") 
print(f"Execution Time: {end_time - start_time:.4f} seconds") # .4f → means “show 4 digits after the decimal point.

Total: 4999999950000000
Execution Time: 43.36258888244629 seconds
Execution Time: 43.3626 seconds


In [6]:
numbers = np.arange(1, 100000000)
start_time = time.time()
total = np.sum(numbers)
end_time = time.time()
print("Total:", total)
print(f"Execution Time: {end_time - start_time:.4f} seconds")

Total: 4999999950000000
Execution Time: 0.0870 seconds


In [7]:
list1 = [10,"Python",89.21]
print(list1)

[10, 'Python', 89.21]


In [8]:
arr = np.array([10,"Python",89.21])
print(arr)

['10' 'Python' '89.21']


In [9]:
# Array
# In programming, an array is a data structure used to store a collection of elements,
# or values, of the same data type under a single variable name.

# Array : Single Dimensional (1D) and Multi Dimensional (2D)

# How to create a 1D array
# array() used to create 1D or 2D array

arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [10]:
# shape property
# used to determine the dimensions of an array
# For 1D array return (n,)    --> where n is the number of elements
# For 2D array return (n,m)   --> where n is the number of row and m is the number of column
print(arr.shape)

(6,)


In [11]:
# Create a 2D Array
twod = np.array([[1,2],[3,4],[5,6]])
print(twod)
print(twod.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [12]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)

# Indexing and Slicing
print(arr[2])
print(arr[-1])
print(arr[2:7])
print(arr[::-1])
print(arr[2:7:2])

[10 20 30 40 50 60 70 80 90]
30
90
[30 40 50 60 70]
[90 80 70 60 50 40 30 20 10]
[30 50 70]


In [13]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod)
print(twod[0,0])  # [row column] 
print(twod[2,1])

# Show me 1st row only
print(twod[0])

# Show me 2nd column
print(twod[:,1])

# show me the last row
print(twod[2,:])

# show me the first 2 rows
print(twod[0:2,:])

[[1 2]
 [3 4]
 [5 6]]
1
6
[1 2]
[2 4 6]
[5 6]
[[1 2]
 [3 4]]


In [14]:
# Numpy Data Types
arr = np.array([10,20,30,40])
print(arr.dtype)  # dtype property helps us to determine the data type of an array

int64


In [15]:
arr = np.array([10.1,20.2,30.3,40.4])
print(arr.dtype)  # dtype property helps us to determine the data type of an array

float64


In [16]:
arr = np.array([True,False,True])
print(arr.dtype)  # dtype property helps us to determine the data type of an array

bool


In [17]:
arr = np.array(['apple is nice food','banana','cherry'])
print(arr.dtype)  # dtype property helps us to determine the data type of an array
# <U --> Unicode string
# 18 --> max length of a string

<U18


In [18]:
# using dtype for conversion
arr = np.array([1,2,3,4,5],dtype='f4')   # 2 bytes --> Bytes into Bits --> 16 [1byte = 8bits]
print(arr.dtype)

float32


In [19]:
# astype() used for conversion
arr = np.array([1,2,3,4,5])
arr = arr.astype('f8')             # f --> float   f4 --> float32bits   f8 --> float64bits
print(arr.dtype)

float64


In [20]:
# numpy copy() vs view()

# copy()
# a copy will create a new independent array in a different memory location

org_arr = np.array([1,2,3,4,5])
copied_arr = org_arr.copy()
print(copied_arr)

# if you make changes in copied_arr , it won't affect the original array

copied_arr[0] = 100
print(copied_arr)
print(org_arr)

# if you make changes in org_arr , it won't affect the copied array

org_arr[2] = 300
print(org_arr)
print(copied_arr)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[  1   2 300   4   5]
[100   2   3   4   5]


In [22]:
# view()
# a view is the representation of the original array
# it shares the same memory location

org_arr = np.array([1,2,3,4,5])
copied_arr = org_arr.view()
print(copied_arr)

# if you make changes in copied_arr , it will affect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_arr)

# if you make changes in org_arr , it will affect the copied array

org_arr[2] = 300
print(org_arr)
print(copied_arr)

[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]
[100   2 300   4   5]
[100   2 300   4   5]


In [23]:
org_arr = np.array([1,2,3,4,5])
copied_arr = org_arr.view()

# shares_memory() --> returns True if arrays are sharing same memory location

print(np.shares_memory(org_arr,copied_arr))

True


In [24]:
# Numpy Array Reshaping  --> Converting 1D into 2D  or  2D into 1D
# reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   # 2x6  6x2  3x4  4x3  12x1  1x12

twod = arr.reshape(3,4)
print(twod)

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])   # 1x13  13x1
twod = arr.reshape(13,1)
print(twod)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# numpy.newaxis
# is used to increase the dimension of the existing array by one more dimension meaning
# 1D array will become 2D array
arr[:,np.newaxis]  # Column vector

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
arr[np.newaxis,:] # Row vector

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [28]:
# converting 2d into 1d
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)

ar = twod.reshape(6)
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [29]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
ar = twod.reshape(-1)
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [30]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
ar = twod.flatten()
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [31]:
# concatenate()
# used to join 2 arrays

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,9,10])
arr = np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [33]:
# array_split()
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.array_split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [34]:
# Sorting
# np.sort()   # by default ascending order
prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices))

[ 12  34  34  34  56  67  78  90  95 102 120 172]


In [35]:
prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices)[::-1])  # descending order

[172 120 102  95  90  78  67  56  34  34  34  12]


In [36]:
# Filter and searching in Numpy
arr = np.array([1,4,2,7,9,3,5,8])
print(arr)

for i in arr:
    if i>=5:
        print(i)

[1 4 2 7 9 3 5 8]
7
9
5
8


In [37]:
# boolean masking
res = arr>=5
print(res)

[False False False  True  True False  True  True]


In [38]:
arr = np.array([1,4,2,7,9,3,5,8])
newarr = arr[arr>=5]
print(newarr)

[7 9 5 8]


In [39]:
# np.where(exprsn)
# np.where returns IndexNumbers 
arr = np.array([1,4,2,7,9,3,5,8])
res = np.where(arr>=5)
print(res)
print(arr[res])

(array([3, 4, 6, 7]),)
[7 9 5 8]


In [41]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
 
# Find indices where value is 30
indices = np.where(arr == 30)
print(f"Indices where value is 30: {indices}")
 
# Find indices where values are even
even_indices = np.where(arr % 2 == 0)
print(f"Indices of even values: {even_indices}")
 
# Conditional selection
new_arr = np.where(arr > 40, arr * 2, arr)
print(f"Array after conditional selection: {new_arr}")

Indices where value is 30: (array([2]),)
Indices of even values: (array([0, 1, 2, 3, 4, 5]),)
Array after conditional selection: [ 10  32  30 100  20 164 182  90]


In [42]:
# Numpy Random Module
from numpy import random
x = random.randint(100)   # 1 till 100
print(x)

36


In [43]:
x = random.randint(100,150)  # 100 till 150
print(x)

118


In [44]:
# generate random float
# rand() method returns a random float value between 0 and 1
print(random.rand())

0.708277407037306


In [45]:
# generating random 1d array
x = random.randint(30,70,size=(5))
print(x)

[57 55 47 40 42]


In [46]:
# generating random 2d array
x = random.randint(30,70,size=(3,4))
print(x)

[[62 59 57 39]
 [69 40 44 61]
 [34 66 68 63]]


In [47]:
x = random.randint(100,size=(3,4))
print(x)

[[46 43 37 20]
 [ 6 79 59 23]
 [39 44  6 19]]


In [48]:
x = random.rand(8)
print(x)

[0.84818959 0.8665711  0.42618752 0.22193631 0.77279169 0.10872705
 0.38221546 0.09974447]


In [49]:
x = random.rand(3,5)
print(x)

[[0.64915375 0.58108298 0.80959437 0.7280156  0.85813778]
 [0.13945691 0.49615603 0.43717215 0.82447739 0.36845418]
 [0.63106599 0.14650747 0.91046168 0.011773   0.65757077]]


In [50]:
# The choice() method allows you to generate a random value
# based on an array of values.
x = random.choice([3,5,7,9])
print(x)

5


In [51]:
x = random.choice([3,5,7,9],size=(12))
print(x)

[9 9 7 7 9 5 9 3 5 9 5 5]


In [52]:
x = random.choice([3,5,7,9],size=(3,4))
print(x)

[[3 7 5 7]
 [3 7 3 5]
 [5 9 3 5]]


In [53]:
# numpy.zeros()
# this function allows us to create an array filled with Zero's
# default data type will be FLOAT

arr = np.zeros(12,dtype='i')
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0]


In [54]:
arr = np.zeros((3,5),dtype='i')
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [55]:
# numpy.ones()
# this function allows us to create an array filled with One's
# default data type will be FLOAT

arr = np.ones(12,dtype='i')
print(arr)

[1 1 1 1 1 1 1 1 1 1 1 1]


In [56]:
# numpy.sum()
# used to compute the sum of all elments
x = np.random.randint(50,size=(12))
print(x)

[17 43  8 13 27 35 33 14 38 33 36 15]


In [57]:
print(np.sum(x))

312


In [58]:
# numpy.mean()
# mean value is the average value
print(np.mean(x))

26.0


In [59]:
# numpy.mode()
# the mode value is the value that appears most number of times
from scipy import stats
print(stats.mode(x))

ModeResult(mode=np.int32(33), count=np.int64(2))


In [60]:
# numpy.unique()
# return unique elements as a sorted array
a = np.unique([1,2,3,4,1,2,1,1,1,5,6,7,5,9,10,11,8,6,5])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [61]:
arr = np.array([1,2,3,4,1,2,1,1,1,5,6,7,5,9,10,11,8,6,5])
# 1 2 3 4 5 6 7 9 10 11 8
uv , i = np.unique(arr,return_index=True)

# return_index=True gives you 2 things
# a.) unique value   -->  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11
# b.) index numbers   --> 0,  1,  2,  3,  9, 10, 11, 16, 13, 14, 15
#     first occurence

In [62]:
# argsort --> reorder based on original appearance
uv[np.argsort(i)]

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 11,  8])

In [63]:
# arange()
print(np.arange(11))
print(np.arange(1,11))
print(np.arange(1,11,3))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [64]:
print(np.arange(4).reshape(2,2))

[[0 1]
 [2 3]]


In [65]:
# numpy broadcasting
arr1 = np.array([4,5,7,8])
arr2 = np.array([8,1,3,4])
print(arr1 + arr2)

[12  6 10 12]


In [66]:
# if we try to perform arithmetic operation 
# b/w uncompatible shapes 

arr1 = np.array([4,5,7,8])
arr2 = np.array([8,1,3])
print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [68]:
# if any one of them is 1 

arr1 = np.array([4,5,7,8])
arr2 = np.array([8])
print(arr1 + arr2)

[12 13 15 16]
